name: Create Release
permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    container: python:3.6
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          make dev

      - name: Verify tag version matches package version
        run: |
          # Get version using pkg_resources
          PKG_VERSION=$(python -m rlc.cloud_repos 2>/dev/null)
          # Extract tag version (remove 'v' prefix)
          TAG_VERSION=${GITHUB_REF#refs/tags/v}

          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
            echo "ERROR: Version mismatch: Tag version ($TAG_VERSION) does not match package version ($PKG_VERSION)"
            exit 1
          fi

      - name: Build distribution
        run: |
          make sdist
          make dist

      - name: Generate RPM spec file
        run: make spec

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          name: Release ${{ github.ref_name }}
          files: |
            dist/*.tar.gz
            dist/*.whl
            dist/*.spec
